name: "builds & tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -DBUILD_TESTS=YES -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: 
      run: ctest --output-on-failure --test-dir ${{github.workspace}}/build
  build:
   strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build
